# -*- coding: utf-8 -*-
"""BOJ/doyoonKim/week6/6주차스터디.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bLlYqGBXPPnB0R54bii1GbCxl29SfR2

# 6/20~6/22
dp 구현

## 피보나치 수 2
2748
약 5분
"""

Lfibo = [0,1] # dp 이용 F_0 = 0, F_1 = 1
n = int(input())
while n>=len(Lfibo):
  Lfibo.append(Lfibo[-1]+Lfibo[-2])
print(Lfibo[n])

"""## 계단 오르기
2579
50분
"""

n = int(input())
stairs = []
for i in range(n):
  stairs.append(int(input()))
print(step(stairs, n))

def step(stairs, n):
  if n==1:
    return stairs[0]
  elif n ==2:
    return stairs[0]+stairs[1]
  elif n==3:
    return stairs[2]+max(stairs[0], stairs[1])
  else:
    new_steps = [0]*n
    new_steps[0] = stairs[0]
    new_steps[1] = stairs[0]+stairs[1]
    new_steps[2] = max(stairs[0], stairs[1])+stairs[2]
    for i in range(3,n):
      new_steps[i] = stairs[i] + max(new_steps[i-2], new_steps[i-3]+stairs[i-1])
  return new_steps[n-1]

"""## 2xn 타일링
11726
5분
"""

n = int(input())
answer = [1,2]
if n>2:
  for i in range(2,n+1):
    answer.append((answer[i-1]+answer[i-2])%10007)
print(answer[n-1])